# Generated by Django 4.0.4 on 2022-05-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='category',
            new_name='source',
        ),
    ]
